version: "3.23"
services:
  db1:
    image: ghcr.io/hydradatabase/hydra:latest
    container_name: db1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  vmsamp:
    build:
      context: ./python
      dockerfile: ./Dockerfile
    container_name: vm_cont1
    environment:
      POSTGRES_DB: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
    depends_on:
      - db1
  streamlit:
    container_name: streamlit
    build:
      context: ./streamlit
      dockerfile: ./Dockerfile
    ports:
      - 8501:8501
